name: anga
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.3.0

  # Charts for weather visualization
  fl_chart: ^0.70.2

  # Animations
  animate_do: ^4.2.0

  # Date formatting
  intl: ^0.20.2 

  # Auto-suggestions (Typeahead)
  flutter_typeahead: ^5.2.0

  # Local storage for user preferences
  shared_preferences: ^2.2.2

  # Page transitions
  page_transition: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for best practices
  flutter_lints: ^5.0.0

flutter:
  # ✅ Ensure Material icons are enabled
  uses-material-design: true

  # ✅ Declare assets (images, icons, fonts)
  assets:
    - assets/images/farming.jpg
    

