// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nsfizbR49LwKoS_2w75Fsc1v4Xfn6Yc',
    appId: '1:787124550080:web:26252c2de7b6da7c997025',
    messagingSenderId: '787124550080',
    projectId: 'anga-744bd',
    authDomain: 'anga-744bd.firebaseapp.com',
    storageBucket: 'anga-744bd.firebasestorage.app',
    measurementId: 'G-JETBGW3YSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0v1vhKMFBt28rNbcmLZ38UKyDPIBiLhg',
    appId: '1:787124550080:android:0ddb97f161629635997025',
    messagingSenderId: '787124550080',
    projectId: 'anga-744bd',
    storageBucket: 'anga-744bd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2nsfizbR49LwKoS_2w75Fsc1v4Xfn6Yc',
    appId: '1:787124550080:web:ceb58fc0f18ad7c9997025',
    messagingSenderId: '787124550080',
    projectId: 'anga-744bd',
    authDomain: 'anga-744bd.firebaseapp.com',
    storageBucket: 'anga-744bd.firebasestorage.app',
    measurementId: 'G-GE8GS68B7B',
  );
}
